name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout bleu's version of Balancer SOR
        uses: actions/checkout@v3
        with:
          repository: bleu-studio/balancer-sor
          path: balancer-sor

      - uses: actions/checkout@v3

      - uses: ./.github/workflows/setup-pnpm

      - name: Check formatting and linting
        run: pnpm ci
