name: test

on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

defaults:
  run:
    shell: bash
    working-directory: ./packages/contracts

jobs:
  foundry:
    name: Foundry project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup-pnpm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test

  hardhat:
    name: Hardhat project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup-pnpm

      - name: Run Hardhat tests
        run: |
          pnpm hardhat test
        id: hardhat-test
