name: test

on:
  push:
    branches:
      - main
    paths:
      - "packages/contracts/**"
  pull_request:
    paths:
      - "packages/contracts/**"

env:
  FOUNDRY_PROFILE: ci

defaults:
  run:
    shell: bash
    working-directory: ./packages/contracts

jobs:
  foundry:
    name: Foundry project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup-pnpm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test
