name: Daily APR ETL Process

on:
  schedule:
    - cron: "30 0 * * *" # Runs at 00:30 UTC every day
  workflow_dispatch:

jobs:
  run_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.14.0"

      - name: Set up pnpm
        uses: ./.github/workflows/setup-pnpm

      - name: Install Dependencies
        run: pnpm install
        working-directory: ./packages/balancer-apr

      - name: Test Node.js Execution
        run: node -e "console.log('Node.js is working')"
        working-directory: ./packages/balancer-apr

      - name: Run ETL Process
        env:
          DATABASE_URL: ${{ secrets.APR_DATABASE_URL }}
          IS_GITHUB: ${{ secrets.IS_GITHUB }}
        run: |
          echo "Running ETL Process..."
          node -r esbuild-register src/index.ts
        working-directory: ./packages/balancer-apr
