name: Deploy PR preview app to Fly

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - "packages/next-app/**"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  preview_app:
    runs-on: ubuntu-latest
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}
      cancel-in-progress: true
    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: bleu-balancer-tools-pr-${{ github.event.number }}-preview
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@1.0.0
        with:
          name: bleu-balancer-tools-pr-${{ github.event.number }}-preview
          org: bleu

      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v2
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          name: bleu-balancer-tools-pr-${{ github.event.number }}-preview
          org: bleu
