name: Deploy to Fly

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy next-app
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    environment:
      name: production
      url: ${{ steps.step_id.outputs.url_output }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
