name: Deploy Graph

on:
  workflow_dispatch:

jobs:
  deploy-goerli:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/setup-pnpm

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Codegen
        working-directory: ./packages/subgraph
        run: pnpm codegen

      - name: Build
        working-directory: ./packages/subgraph
        run: pnpm build subgraph.goerli.yaml

      - uses: gtaschuk/graph-deploy@v0.1.12
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "balancer-pools-metadata"
          graph_account: "bleu-llc"
          graph_config_file: "./packages/subgraph/subgraph.goerli.yaml"
env:
  CI: true
